import { useEffect, useMemo, useRef, useState } from 'react';
import { dataService } from '../../services/dataService';
import { aiService } from '../../services/aiService';
import { microsoftAuth, MicrosoftAuthError } from '../../services/microsoftAuth';
import { outlookService, OutlookError } from '../../services/outlookService';
import { OUTLOOK_CONNECTED_KEY } from '../settings/Connections';
import { Drawer, Chip, Button, Dialog, Textarea, useToast } from '../../ui';
import { cx } from '../bench/lib/tokens';
import { touchWarmth } from '../bench/lib/actions';
import { useSequence, saveStepDraft, markStepSent } from './lib/sequence';
import { SETTINGS_KEYS } from '../../types';
import type { OutreachRequestBody } from '../../types';

export interface OutreachComposerProps {
  candidateId: string;
  roleId?: string;
  onClose: () => void;
}

type Tone = OutreachRequestBody['tone'];
type Step = 0 | 3 | 7;
const STEPS: { day: Step; label: string }[] = [
  { day: 0, label: 'Day 0 · Email' },
  { day: 3, label: 'Day 3 · Nudge' },
  { day: 7, label: 'Day 7 · LinkedIn' },
];

/**
 * Streaming outreach composer per BLUEPRINT-v2.md: tone chips, editable Day 0/3/7 sequence,
 * Copy / Open in mail app / Mark sent (resets warmth, schedules the next step). Never sends
 * automatically — every send is the human clicking a mailto link or their own mail client.
 */
export function OutreachComposer({ candidateId, roleId, onClose }: OutreachComposerProps) {
  const candidate = dataService.hooks.useCandidate(candidateId);
  const role = dataService.hooks.useRole(roleId);
  const processes = dataService.hooks.useProcessesForCandidate(candidateId) ?? [];
  const matches = dataService.hooks.useMatchesForRole(roleId) ?? [];
  const match = matches.find(m => m.candidateId === candidateId);
  const seq = useSequence(candidateId, roleId);

  const [tone, setTone] = useState<Tone>('warm');
  const [step, setStep] = useState<Step>(0);
  // Only steps the user has actively edited or streamed *this session* live here — anything
  // else reads straight from the persisted sequence, so there's no hydration effect to write.
  const [edits, setEdits] = useState<Partial<Record<Step, string>>>({});
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoGenerated = useRef(false);
  const { push } = useToast();

  const outlookConnected = dataService.hooks.useSetting<boolean>(OUTLOOK_CONNECTED_KEY, false);
  const allowSend = dataService.hooks.useSetting<boolean>(SETTINGS_KEYS.outlookAllowSend, false);
  const [outlookBusy, setOutlookBusy] = useState<'draft' | 'send' | null>(null);
  const [sendConfirmOpen, setSendConfirmOpen] = useState(false);

  const reason = match?.why ?? processes[0]?.reason ?? '';

  const sentDays = useMemo(
    () => new Set((seq?.steps ?? []).filter(s => s.doneAt).map(s => s.day as Step)),
    [seq],
  );

  const draftFor = (s: Step) => edits[s] ?? seq?.steps.find(x => x.day === s)?.body ?? '';

  const generate = async (targetStep: Step) => {
    if (!candidate || !role) return;
    setGenerating(true);
    setError(null);
    setEdits(prev => ({ ...prev, [targetStep]: '' }));
    try {
      const full = await aiService.draftOutreach(
        {
          candidateName: candidate.name,
          roleTitle: role.title,
          tone,
          reason: reason || 'No prior process on file — a fresh, honest introduction.',
          candidateNotes: candidate.notes[candidate.notes.length - 1]?.body,
          sequenceStep: targetStep,
        },
        chunk => setEdits(prev => ({ ...prev, [targetStep]: (prev[targetStep] ?? '') + chunk })),
      );
      if (roleId) await saveStepDraft(candidateId, roleId, targetStep, full);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Can't reach the AI service right now — check your connection and try again.");
    } finally {
      setGenerating(false);
    }
  };

  // Auto-generate the Day 0 draft once, when we have enough context and nothing saved yet.
  // The call is deferred to a microtask so the effect body itself never calls setState
  // synchronously (react-hooks/set-state-in-effect) — `generate` still runs this tick.
  useEffect(() => {
    if (autoGenerated.current || !candidate || !role || !seq) return;
    autoGenerated.current = true;
    if (!seq.steps.find(s => s.day === 0)?.body) {
      queueMicrotask(() => { void generate(0); });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [candidate, role, seq]);

  const draft = draftFor(step);
  const alreadySent = sentDays.has(step);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(draft);
    } catch {
      /* clipboard may be unavailable — the textarea text is still selectable */
    }
    if (roleId) await saveStepDraft(candidateId, roleId, step, draft);
    await dataService.logActivity({
      candidateId, roleId, type: 'email_copied', actor: 'owner',
      body: `Copied the Day ${step} draft`,
    });
  };

  /** Shared by mailto and both Outlook actions — a leading "Subject: ..." line becomes the
   * real subject; otherwise falls back to a role-shaped default, same as before Outlook. */
  const parseDraft = (text: string): { subject: string; body: string } => {
    const lines = text.split('\n');
    const hasSubject = lines[0]?.toLowerCase().startsWith('subject:');
    const subject = hasSubject ? lines[0].slice(8).trim() : `${role?.title ?? 'A role'} — worth a chat?`;
    const body = hasSubject ? lines.slice(1).join('\n').trim() : text;
    return { subject, body };
  };

  const openInMail = () => {
    const { subject, body } = parseDraft(draft);
    const mailto = `mailto:${encodeURIComponent(candidate?.email ?? '')}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailto;
  };

  /** Graph mail token for the currently signed-in Microsoft account, or a friendly error. */
  const getMailToken = async (): Promise<string> => {
    const token = await microsoftAuth.getToken(microsoftAuth.GRAPH_SCOPES.mail);
    if (!token) throw new MicrosoftAuthError('Sign in with Microsoft in Settings → Connections first.');
    return token;
  };

  const htmlBody = (body: string): string =>
    body.split('\n').map(line => `<p>${line.replace(/&/g, '&amp;').replace(/</g, '&lt;') || '&nbsp;'}</p>`).join('');

  /** "Create draft in Outlook" — DESIGN-v2.1.md §A: Graph POST /me/messages, opens the draft
   * in Outlook web via its webLink. Creates, never sends. */
  const createOutlookDraft = async () => {
    if (!candidate?.email) { setError('This candidate has no email on file.'); return; }
    setOutlookBusy('draft'); setError(null);
    try {
      const token = await getMailToken();
      const { subject, body } = parseDraft(draft);
      const result = await outlookService.createDraft(token, { to: candidate.email, subject, html: htmlBody(body) });
      await dataService.logActivity({ candidateId, roleId, type: 'email_drafted', actor: 'owner', body: `Created an Outlook draft — "${subject}"` });
      window.open(result.webLink, '_blank', 'noopener');
      push('Draft created in Outlook.', { tone: 'success' });
    } catch (e) {
      setError(e instanceof MicrosoftAuthError || e instanceof OutlookError ? e.message : 'Could not create the Outlook draft.');
    } finally {
      setOutlookBusy(null);
    }
  };

  /** "Send from Outlook" — only reachable when allowSend is on; still confirms, since this is
   * the one composer action with real consequences. outlookService.sendDraft logs email_sent. */
  const sendFromOutlook = async () => {
    if (!candidate?.email) { setError('This candidate has no email on file.'); return; }
    setSendConfirmOpen(false);
    setOutlookBusy('send'); setError(null);
    try {
      const token = await getMailToken();
      const { subject, body } = parseDraft(draft);
      const created = await outlookService.createDraft(token, { to: candidate.email, subject, html: htmlBody(body) });
      await outlookService.sendDraft(token, created.id, candidateId);
      if (roleId) await markStepSent(candidateId, roleId, step, draft);
      await touchWarmth(candidateId);
      if (match && match.stage === 'warm') await dataService.setStage(match.id, 'reached_out', '');
      push('Sent from Outlook.', { tone: 'success' });
    } catch (e) {
      setError(e instanceof MicrosoftAuthError || e instanceof OutlookError ? e.message : 'Could not send from Outlook.');
    } finally {
      setOutlookBusy(null);
    }
  };

  const markSent = async () => {
    if (!roleId) return;
    await markStepSent(candidateId, roleId, step, draft);
    await touchWarmth(candidateId);
    if (match && match.stage === 'warm') await dataService.setStage(match.id, 'reached_out', '');
    // sentDays is derived from `seq`, which re-reads live once markStepSent's write lands.
  };

  return (
    <Drawer
      open
      onClose={onClose}
      title="Outreach"
      subtitle={candidate ? `To ${candidate.name}${role ? ` — ${role.title}` : ''}` : undefined}
      width={460}
    >
      <div className="flex h-full min-h-0 flex-col gap-4">
        {!roleId && (
          <p className={`rounded-[8px] border p-2 text-xs ${cx.border} ${cx.amberText}`}>
            No role selected — pick one from the top bar so drafts can be saved to a sequence.
          </p>
        )}

        <div className="flex gap-2">
          {(['warm', 'direct', 'short'] as Tone[]).map(t => (
            <Chip key={t} tone="accent" selected={tone === t} onClick={() => { setTone(t); void generate(step); }}>
              {t[0].toUpperCase() + t.slice(1)}
            </Chip>
          ))}
        </div>

        <div role="tablist" aria-label="Sequence step" className="flex gap-1">
          {STEPS.map(s => (
            <button
              key={s.day}
              role="tab"
              aria-selected={step === s.day}
              onClick={() => setStep(s.day)}
              className={`relative rounded-[6px] px-2.5 py-1.5 text-xs font-medium ${cx.focusRing} ${
                step === s.day ? `${cx.accentBg} text-black` : `${cx.muted} hover:bg-[var(--panel-2,#1c2127)]`
              }`}
            >
              {s.label}
              {sentDays.has(s.day) && <span className="ml-1">✓</span>}
            </button>
          ))}
        </div>

        {error && (
          <p role="alert" className={`rounded-[8px] border p-2 text-xs ${cx.border} ${cx.dangerText}`}>
            {error}
          </p>
        )}

        <Textarea
          label={`Draft — ${STEPS.find(s => s.day === step)?.label}`}
          value={draft}
          onChange={e => setEdits(prev => ({ ...prev, [step]: e.target.value }))}
          onBlur={() => roleId && saveStepDraft(candidateId, roleId, step, draft)}
          rows={12}
          placeholder={generating ? 'Writing…' : 'Click Regenerate to draft this step.'}
          hint={generating ? 'Streaming…' : undefined}
        />

        <div className="flex flex-wrap gap-2">
          <Button variant="secondary" onClick={() => generate(step)} loading={generating} disabled={!candidate || !role}>
            {draft ? 'Regenerate' : 'Generate'}
          </Button>
          <Button variant="secondary" onClick={copy} disabled={!draft}>Copy</Button>
          <Button variant="secondary" onClick={openInMail} disabled={!draft}>Open in mail app</Button>
          <Button
            variant="secondary"
            onClick={createOutlookDraft}
            loading={outlookBusy === 'draft'}
            disabled={!outlookConnected || !draft || !candidate?.email}
            title={outlookConnected ? undefined : 'Connect Outlook in Settings → Connections to enable this'}
          >
            Create draft in Outlook
          </Button>
          {outlookConnected && allowSend && (
            <Button variant="secondary" onClick={() => setSendConfirmOpen(true)} loading={outlookBusy === 'send'} disabled={!draft || !candidate?.email}>
              Send from Outlook
            </Button>
          )}
          <Button variant="primary" onClick={markSent} disabled={!draft || !roleId || alreadySent}>
            {alreadySent ? 'Marked sent ✓' : 'Mark sent'}
          </Button>
        </div>

        {!outlookConnected && (
          <p className={`text-xs ${cx.muted}`}>
            Outlook isn't connected on this deployment yet — Create draft in Outlook stays off until
            you register the app and set VITE_MS_CLIENT_ID (Settings → Connections has the exact steps).
            Copy and Open in mail app still work.
          </p>
        )}

        {alreadySent && (
          <p className={`text-xs ${cx.muted}`}>
            Warmth reset and the next step is scheduled as a reminder. This composer never sends on its own —
            sending happens in your mail client.
          </p>
        )}
      </div>

      <Dialog
        open={sendConfirmOpen}
        onClose={() => setSendConfirmOpen(false)}
        title={`Send this to ${candidate?.name ?? 'them'} right now?`}
        footer={
          <>
            <Button variant="ghost" onClick={() => setSendConfirmOpen(false)}>Cancel</Button>
            <Button variant="primary" onClick={sendFromOutlook} loading={outlookBusy === 'send'}>Send from Outlook</Button>
          </>
        }
      >
        <p className={cx.muted}>
          This actually leaves your Outlook mailbox — {candidate?.email}. There's no undo. Copy or
          Create draft stay available if you'd rather review it in Outlook first.
        </p>
      </Dialog>
    </Drawer>
  );
}
